apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: logging-solution
  labels:
    k8s-app: elasticsearch
spec:
  selector:
    k8s-app: elasticsearch
  clusterIP: None
  ports:
  - port: 9200
    name: rest
  - port: 9300
    name: inter-node
