apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: logging-solution
  labels:
    k8s-app: kibana
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  ports:
  - port: 5601
  selector:
    k8s-app: kibana
    addonmanager.kubernetes.io/mode: Reconcile