apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: logging-solution
  labels:
    k8s-app: kibana
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kibana
  template:
    metadata:
      labels:
        k8s-app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.17.0 #endpoint and port for the Elasticsearch cluster
        resources:
          #limits:
            #cpu: 1000m
          #requests:
           # cpu: 100m
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch:9200
        ports:
        - containerPort: 5601 